### ISSUE TITLE
Add ability to pass proxies via input file

### ISSUE THREAD

**Issue by alexgarciab** [ApsOps/proxy-checker#2]
Hi there, would it be possible to add the ability to pass the proxies via file instead of an array inside the code?

Thanks!

**Comment by AmirTyper** [comment]
@alexgarciab you can use this: [https://github.com/Amirtyper/Proxy-Checker](url)

**Comment by FeelsBadMan1** [comment]
Hey, yea a proxyfile wouöd be great and using the format user:pass@ip:port would be great too
